version: '3'
volumes:
  dbdata:
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: webapp
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: webserver
    working_dir: /var/www
    volumes:
      - app
    ports:
      - 8080:80
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
